### PR TITLE
Replace 'pitzdir' as a name of the default dir with '.pitz'

### PR DESCRIPTION
**Pull request by mcepl**
visible directories in a project are evil (see ./CVS|./RCS story).

### CODE REVIEW

**Comment by mw44118** [comment]
I tried to do .pitz, but I could never figure out how to import from a folder that begins with a "." character.  Thanks so much for the pull request!  I will look at it now and figure out how you did it.

Matt

**Comment by mcepl** [comment]
Hmm, then I am not sure whether I have fixed it at all. Why do you need to import from a data directory anyway?

**Comment by mw44118** [comment]
You might be correct on that point -- maybe I do not need to import code
from that folder.

Do all the tests pass for you after you apply your change?

**Comment by mcepl** [comment]
Hmm, it doesn't ... https://github.com/mcepl/pitz/blob/e26b27a3b9ed42d9284094a7fce2228424791b0e/test-log-pitzdir.txt
I will work on it to fix those failures.

**Comment by mw44118** [comment]
Those might be fixable.  Maybe the "pitzdir" folder is hard-coded in the
setup and teardown methods.

Matt

**Comment by mcepl** [comment]
BTW, travis-CI build of this branch https://travis-ci.org/mcepl/pitz/builds/15131916

**Pull request closed without merging**
